spring.application.name=tms
spring.datasource.url=jdbc:mysql://mysql:3306/tmsdb
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect



secretJwtString : y$R8#mQ2!vK5&zP9_wX1*bN4@tC7^jL0%fU3(hY6)aS9_mK2!vP5&zR8#wX1*bN
